name: Build macOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compilar app
      run: python3 setup.py py2app

    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: mac-app
        path: dist/*.app
